---
name: Development Containers (CI)
on:
  pull_request:
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer-ci.yml
  push:
    branches:
      - main
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer-ci.yml
jobs:
  devcontainer-build:
    uses: Cogni-AI-OU/.github/.github/workflows/devcontainer-ci.yml@main
    permissions:
      contents: read
      packages: write
    with:
      required_commands: docker gh git node npm pre-commit python3 rg
      required_python_packages: ansible ansible-lint docker pre-commit uv
